#! /bin/sh

case "$1" in
	start)
		echo "Starting aesdsocket"
		start-stop-daemon -S -n aesdsocket -- -d -a ./aesdsocket
		;;
	stop)
		echo "Stopping aesdsocket"
		start-stop-daemon -K -n aesdsocket --signal SIGTERM
		;;
	*)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0


